service: lambda-microetl

frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-python-requirements
provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: functions.health_check.hello
    events:
      - httpApi:
          path: /
          method: get
